version: '3.4'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkinsNetlify
    ports:
      - "8084:8084"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # To allow Jenkins to use Docker
volumes:
  jenkins_home: